enum GameStage {
  CONFIGURATION,
    PLACING,
    START,
    MOVE_DECISION,
    AGENTS_MOVING,
    COMMUNICATION,
    CLUSTERING,
    VOTING,
    MONUMENT_MOVE_DECISION,
    MONUMENTS_MOVING,
    FINISH
}
